postgres:
    database: aioweb
    user: root
    password: '123456'
    host: '127.0.0.1'
    port: 5432
    minsize: 1
    maxsize: 5

mysql:
    database: aioweb
    user: root
    password: '123456'
    host: '127.0.0.1'
    port: 3306
    minsize: 1
    maxsize: 5

redis:
    address: 'redis://root:@127.0.0.1:6379/0'
    timeout: 3600